services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
      - /app/.venv
    environment:
      - ENVIRONMENT=development
      - JWT_SECRET_KEY=98bc1394597c84a27a3f23f443347386d67ce2a3d0d9cfa5407a0b62024e3abd
      - JWT_REFRESH_SECRET_KEY=91ce94423fd380476d4d04efba6321d420b193b9683737fab349d59daaa3cec3

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # - WATCHPACK_POLLING=true  # uncomment if hot reload is broken on macOS/Windows
