export const routes = {
  home:               '/',
  login:              '/login',
  privacy:            '/privacy',
  unauthorized:       '/unauthorized',
  survey:             '/survey',
  dashboard:          '/dashboard',
  events:             '/events',
  eventDetail:        (id: number) => `/events/${id}`,
  sports:             '/sports',
  sportDetail:        (id: number) => `/sports/${id}`,
  users:              '/users',
  organizations:      '/organizations',
  participation:      '/participation',
  sportSubmissions:   '/sport-submissions',
  categorySubmissions: '/category-submissions',
  cards:              '/cards',
  reports:            '/reports',
  register:           '/register',
  leaderRegistration: '/leader-registration',
  registrations:      '/registrations',
  registrationDetail: (id: number) => `/registrations/${id}`,
  byNumber:           '/by-number',
  byCategory:         '/by-category',
  bySport:            '/by-sport',
  openSurvey:         '/open-survey',
  openSurveyFields:   '/open-survey/fields',
} as const;


