"""initial_schema

Revision ID: 425f25068de6
Revises: 
Create Date: 2026-06-04 10:58:54.024789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425f25068de6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('target_enroll_id', sa.Integer(), nullable=False),
    sa.Column('fields', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_access_logs_actor_user_id'), 'pii_access_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_pii_access_logs_target_enroll_id'), 'pii_access_logs', ['target_enroll_id'], unique=False)
    op.add_column('users', sa.Column('token_valid_from', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'organization', 'federation', name='user_role'),
               type_=sa.Enum('super_admin', 'admin', 'organization', 'federation', name='user_role', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'organization'::user_role"))
    op.create_index(op.f('ix_users_sport_id'), 'users', ['sport_id'], unique=False)

    # Performance indexes (001_add_indexes.sql)
    # Note: CONCURRENTLY omitted — this migration runs inside a transaction.
    # On high-traffic production DBs run the raw SQL from 001_add_indexes.sql manually.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_enrollments_phonenumber_trgm "
        "ON enrollments USING gin (phonenumber gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_athlete_participation_org_event "
        "ON athlete_participation (organization_id, events_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_leader_participation_org_event "
        "ON leader_participation (organization_id, events_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_participation_per_sport_org "
        "ON participation_per_sport (org_id)"
    )
    op.execute(
        'CREATE INDEX IF NOT EXISTS idx_participation_per_sport_sports_events '
        'ON participation_per_sport ("sports_Events_id")'
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_sports_event_org_composite "
        "ON sports_event_org (events_id, sports_id, organization_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_sports_event_composite "
        "ON sports_event (events_id, sports_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_enrollments_created_at_desc "
        "ON enrollments (created_at DESC)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_enrollments_kh_name "
        "ON enrollments USING gin (kh_family_name gin_trgm_ops, kh_given_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_enrollments_en_name "
        "ON enrollments USING gin (en_family_name gin_trgm_ops, en_given_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_athlete_participation_sport_event "
        "ON athlete_participation (sports_id, events_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_leader_participation_sport_event "
        "ON leader_participation (sports_id, events_id)"
    )
    # ### end Alembic commands ###


    op.execute(
        "UPDATE users SET token_valid_from = created_at AT TIME ZONE 'UTC' "
        "WHERE token_valid_from IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Performance indexes (001_add_indexes.sql)
    op.execute("DROP INDEX IF EXISTS idx_leader_participation_sport_event")
    op.execute("DROP INDEX IF EXISTS idx_athlete_participation_sport_event")
    op.execute("DROP INDEX IF EXISTS idx_enrollments_en_name")
    op.execute("DROP INDEX IF EXISTS idx_enrollments_kh_name")
    op.execute("DROP INDEX IF EXISTS idx_enrollments_created_at_desc")
    op.execute("DROP INDEX IF EXISTS idx_sports_event_composite")
    op.execute("DROP INDEX IF EXISTS idx_sports_event_org_composite")
    op.execute("DROP INDEX IF EXISTS idx_participation_per_sport_sports_events")
    op.execute("DROP INDEX IF EXISTS idx_participation_per_sport_org")
    op.execute("DROP INDEX IF EXISTS idx_leader_participation_org_event")
    op.execute("DROP INDEX IF EXISTS idx_athlete_participation_org_event")
    op.execute("DROP INDEX IF EXISTS idx_enrollments_phonenumber_trgm")
    op.drop_index(op.f('ix_users_sport_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'organization', 'federation', name='user_role', schema='public'),
               type_=postgresql.ENUM('super_admin', 'admin', 'organization', 'federation', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'organization'::user_role"))
    op.drop_column('users', 'token_valid_from')
    op.drop_index(op.f('ix_pii_access_logs_target_enroll_id'), table_name='pii_access_logs')
    op.drop_index(op.f('ix_pii_access_logs_actor_user_id'), table_name='pii_access_logs')
    op.drop_table('pii_access_logs')
    # ### end Alembic commands ###
