"""add_category_survey_review

Revision ID: fe93a4dc40ad
Revises: c8d9e0f1a2b3
Create Date: 2026-06-17 06:49:29.449789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe93a4dc40ad'
down_revision: Union[str, Sequence[str], None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_survey_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.Column('sports_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='SUBMITTED', nullable=False),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sports_id'], ['sports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('events_id', 'sports_id', name='uix_category_review_event_sport')
    )
    op.create_index(op.f('ix_category_survey_review_events_id'), 'category_survey_review', ['events_id'], unique=False)
    op.create_index(op.f('ix_category_survey_review_id'), 'category_survey_review', ['id'], unique=False)
    op.create_index(op.f('ix_category_survey_review_sports_id'), 'category_survey_review', ['sports_id'], unique=False)
    op.drop_index(op.f('uq_sports_event_org_keys'), table_name='sports_event_org', postgresql_where='((events_id IS NOT NULL) AND (sports_id IS NOT NULL) AND (organization_id IS NOT NULL))')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'organization', 'federation', name='user_role'),
               type_=sa.Enum('super_admin', 'admin', 'organization', 'federation', name='user_role', schema='public'),
               existing_nullable=False,
               existing_server_default=sa.text("'organization'::user_role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'organization', 'federation', name='user_role', schema='public'),
               type_=postgresql.ENUM('super_admin', 'admin', 'organization', 'federation', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'organization'::user_role"))
    op.create_index(op.f('uq_sports_event_org_keys'), 'sports_event_org', ['events_id', 'sports_id', 'organization_id'], unique=True, postgresql_where='((events_id IS NOT NULL) AND (sports_id IS NOT NULL) AND (organization_id IS NOT NULL))')
    op.drop_index(op.f('ix_category_survey_review_sports_id'), table_name='category_survey_review')
    op.drop_index(op.f('ix_category_survey_review_id'), table_name='category_survey_review')
    op.drop_index(op.f('ix_category_survey_review_events_id'), table_name='category_survey_review')
    op.drop_table('category_survey_review')
    # ### end Alembic commands ###
